### PR TITLE
updating for newest React functionality

### PR DESCRIPTION
**Pull request by shodgesio**
The work you've done with the RefTagger is amazing and incredibly useful. I have written the component for React in this way for use on our projects. With a bit more added to props, this can support customization with every property your documentation shows at https://faithlife.com/products/reftagger/customize.

Thank you so much for this excellent API!

### CODE REVIEW

**Comment by shodgesio** [comment]
@davidschwegler just tagging because it looks like this repo might not have any watchers on it at this time.

**Comment by bjclark13** [comment]
@cbleisch-odb you might want to check out @shodgesio's fork to see if you can piggyback off of his work :)

**Comment by davidschwegler** [comment]
@shodgesio Thanks for the PR! Sorry we didn't get to updating this sooner. I've integrated it today, and hope to get the package updated soon (a former employee originally published it under his own account, which we don't have access to, but I'm hoping npm will transfer ownership so we can publish the update).

**Comment by davidschwegler** [comment]
@shodgesio @bjclark13 Published v1.0.0 with these changes!

**Comment by shodgesio** [comment]
Thanks @davidschwegler !

If you'd like the component to be a bit more extensible, I will open a PR implementing the other customizable properties your documentation has listed. Would make sense for them to be passed as props.

**Comment by davidschwegler** [comment]
> Thanks @davidschwegler !
> 
> If you'd like the component to be a bit more extensible, I will open a PR implementing the other customizable properties your documentation has listed. Would make sense for them to be passed as props.

Open to any PR that you would find useful. :)

**Pull request merged**
