### PR TITLE
Enable localization

### LINKED ISSUE #9: Allow localization
The default script URL (https://api.reftagger.com/v2/RefTagger.js) is for English, however refTagger is also available in other languages, via `https://api.reftagger.com/v2/RefTagger.{languageCode}.js`, for example https://api.reftagger.com/v2/RefTagger.es.js.

### PR DESCRIPTION
**Pull request by jameschensmith**
#### Summary

Adds 'language' setting to RefTagger, which enables localization for languages which are supported by the reference tagger API.

Added everyone who contributed to this so far as co-authors. Teamwork makes the dream work :blush:

Closes #9
Closes #10

### CODE REVIEW

**Review by ddunkin — APPROVED** [review]
LGTM

**Comment by jameschensmith** [comment]
@ddunkin, is @davidschwegler still active? I don't see any activity on his profile since February. Just wondering what can be done to get this approved/merged :slightly_smiling_face: Thanks!

**Comment by davidschwegler** [comment]
Hey @jameschensmith , sorry for the delay. I was about to publish this, but I am curious about the languages chosen here. From our FAQ:

https://faithlife.com/products/reftagger/customize
> Does Faithlife Reftagger work with other languages?
Currently, Faithlife Reftagger only supports English and Spanish. If you’d like to see Faithlife Reftagger support another language, please let us know.

Reftagger, in practice, is limited by what Bibles and language support we can deliver to the tooltip, and the routing to Biblia.com if you clicked the link. We can indeed parse / display links for all the languages you've specified in the typescript here, but in Korean, for example, it can't fetch the tooltip contents, and the links to Biblia.com also don't work.

**Comment by ddunkin** [comment]
I provided the list based on what languages we publish scripts for.

**Comment by davidschwegler** [comment]
> I provided the list based on what languages we publish scripts for.

Got it, I see that now, Dave. That will support interface localization moving forward, but it appears additional work is needed for Korean to actually function through the API. I would prefer to only suggest languages (in typescript declarations) to users we have complete/official support for, but I can deploy this as-is if you would prefer.

**Comment by jameschensmith** [comment]
> Hey @jameschensmith , sorry for the delay. I was about to publish this, but I am curious about the languages chosen here. From our FAQ:
> 
> [faithlife.com/products/reftagger/customize](https://faithlife.com/products/reftagger/customize)
> 
> > Does Faithlife Reftagger work with other languages?
> > Currently, Faithlife Reftagger only supports English and Spanish. If you’d like to see Faithlife Reftagger support another language, please let us know.
> 
> Reftagger, in practice, is limited by what Bibles and language support we can deliver to the tooltip, and the routing to Biblia.com if you clicked the link. We can indeed parse / display links for all the languages you've specified in the typescript here, but in Korean, for example, it can't fetch the tooltip contents, and the links to Biblia.com also don't work.
> 
> I'd rather publish this with `language?: 'en' | 'es' | string;` to match our officially supported languages, but pehaps I don't fully understand why you chose to add these additional ones.

@davidschwegler, totally understand your reasoning. I missed this in the FAQ, and followed the languages in the previous PR. I've made the change [here](https://github.com/Faithlife/react-reftagger/pull/12) :+1:

**Pull request merged**
